### ISSUE TITLE
No data symlink in user directory

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasmabio#108]
The `/srv/data` directory is already mapped inside the Docker container.

A `data` symlink seems then not necessary. User will use absolute path to the data: `/srv/data/blabla`. The advantage is that this path will be valid both inside and outside the container (on the host).

**Comment by jtpio** [comment]
I think the reason was to give the user the ability to browse the data folder from the UI by linking it to the home directory.

But having the shared data folder *only* in `/srv/data` in the container would keep things even simpler. So removing the symlink sounds good if we are fine with the users to resort to the terminal (or code) to list the content of the directory and access the files.

**Comment by pierrepo** [comment]
:+1:
